# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'grocery' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for grocery
  pod 'SnapKit', '~> 5.0.0'
  pod 'Hero'
  pod 'SGSwiftExtensions'
  
  target 'groceryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'groceryUITests' do
    # Pods for testing
  end

end
